name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run ci.sh
        run: ./ci.sh
